# Agent Reminder Hook — UserPromptSubmit

**Always generate this hook.** It is foundational to the workflow — without it, Claude drifts from delegation mid-session.

Kept deliberately short — the orchestrator's own system prompt has the full workflow details.

Write to `.claude/hooks/agent-reminder.sh` (or `~/.claude/hooks/` for global). Make it executable (`chmod +x`).

## Reference implementation

Tailor the agents directory path to match the user's installation choice:

```bash
#!/bin/bash
# Generated by setup-agents — agent reminder on every prompt

agents_dir=".claude/agents"
[ -d "$agents_dir" ] || [ -f "$agents_dir/orchestrator.md" ] || exit 0

echo "=== Agent Reminder ==="
echo "For features, bug fixes, or significant changes → delegate to @orchestrator"
echo "It runs the full pipeline (architect → coder → tester → reviewer → design-qa) and returns a concise summary."
echo "Direct access: @architect @coder @tester @reviewer @design-qa"
echo "For quick questions or git ops → handle directly"
echo "=== End Agent Reminder ==="
```

## Register in settings

Always register this in `.claude/settings.local.json`:

```json
{
  "hooks": {
    "UserPromptSubmit": [
      {
        "matcher": "",
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/agent-reminder.sh",
            "timeout": 10
          }
        ]
      }
    ]
  }
}
```

Adjust paths to match the actual installation location. If the settings file already has hooks defined, merge into the existing arrays.
