# Verify Script

**Always generate this for every project that has a test framework.** The verify script is a utility that the **tester agent** runs to identify and execute affected tests. It is NOT a Stop hook — running it on every response is wasteful and slow. Instead, the tester agent calls it as part of its workflow.

Write to `scripts/verify.sh` (or `.claude/hooks/verify.sh`). Make it executable (`chmod +x`).

## What it does

1. Finds all changed files (staged + unstaged) via `git diff`
2. Separates source files from test files
3. Uses CodeGraph (if available) to trace which test files are affected by the source changes — including transitive dependencies not in the diff
4. Falls back to file pattern matching if CodeGraph isn't available
5. Runs ONLY the affected tests — never the full suite
6. Reports pass/fail results
7. Prints a remaining checklist (linter, etc.)

## Placeholders

Tailor the script to the project's actual stack. Replace these placeholders with detected values:

| Placeholder | Example values |
|-------------|---------------|
| `{test_pattern_check}` | `*.spec.*`, `*.test.*`, `*_test.go`, `test_*.py` |
| `{test_glob}` | `e2e/*`, `__tests__/*`, `tests/*`, `src/**/*.test.*` |
| `{test_runner_command}` | `npx playwright test`, `npx jest`, `pytest`, `go test` |
| `{linter_command}` | `shopify theme check`, `npx eslint .`, `ruff check .`, `go vet ./...` |

## Reference implementation

```bash
#!/usr/bin/env bash
# Generated by setup-agents — finds and runs affected tests

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Gather changed files ──
CHANGED=$(git -C "$PROJECT_ROOT" diff --name-only HEAD 2>/dev/null || true)
STAGED=$(git -C "$PROJECT_ROOT" diff --name-only --cached 2>/dev/null || true)
ALL_CHANGED=$(printf '%s\n%s' "$CHANGED" "$STAGED" | sort -u | grep -v '^$' || true)

if [ -z "$ALL_CHANGED" ]; then
  echo "verify: no changes detected, skipping"
  exit 0
fi

# ── Show what changed ──
echo "═══ Changed Files ═══"
echo "$ALL_CHANGED" | sed 's/^/  /'
echo ""

# ── Test file detection ──
is_test_file() {
  case "$1" in
    {test_pattern_check})
      return 0 ;;
    *)
      return 1 ;;
  esac
}

# ── Find affected test files ──
AFFECTED_TESTS=""

# Source-only files (exclude tests) for dependency tracing
SOURCE_FILES=$(echo "$ALL_CHANGED" | while IFS= read -r f; do
  is_test_file "$f" || echo "$f"
done)

# Strategy 1: CodeGraph (traces transitive dependencies)
if command -v codegraph >/dev/null 2>&1 && [ -d "$PROJECT_ROOT/.codegraph" ]; then
  if [ -n "$SOURCE_FILES" ]; then
    CG_RESULTS=$(echo "$SOURCE_FILES" | codegraph affected --stdin --filter "{test_glob}" --quiet --path "$PROJECT_ROOT" 2>/dev/null || true)
    if [ -n "$CG_RESULTS" ]; then
      AFFECTED_TESTS="$CG_RESULTS"
      echo "CodeGraph affected tests:"
      echo "$CG_RESULTS" | sed 's/^/  /'
      echo ""
    fi
  fi
fi

# Strategy 2: Test files directly in the diff
CHANGED_TESTS=$(echo "$ALL_CHANGED" | while IFS= read -r f; do
  is_test_file "$f" && echo "$f"
done || true)

# Combine and deduplicate
ALL_AFFECTED=$(printf '%s\n%s' "$AFFECTED_TESTS" "$CHANGED_TESTS" | sort -u | grep -v '^$' || true)

if [ -z "$ALL_AFFECTED" ]; then
  echo "No affected test files found."
  echo ""
  echo "Remaining checklist:"
  echo "  {linter_command}"
  exit 0
fi

# ── Show affected tests with modification status ──
echo "Affected test files:"
while IFS= read -r test_file; do
  [ -z "$test_file" ] && continue
  if echo "$ALL_CHANGED" | grep -qF "$test_file"; then
    echo "  ✅ $test_file (modified)"
  else
    echo "  ⚠️  $test_file (not updated — may need changes)"
  fi
done <<< "$ALL_AFFECTED"
echo ""

# ── Run affected tests ──
TEST_FILES=$(echo "$ALL_AFFECTED" | tr '\n' ' ')

if [ -n "$TEST_FILES" ]; then
  echo "═══ Running Affected Tests ═══"
  cd "$PROJECT_ROOT"
  {test_runner_command} $TEST_FILES 2>&1
  TEST_EXIT=$?
  echo ""

  if [ $TEST_EXIT -ne 0 ]; then
    echo "🛑 BLOCKED: Tests failed. Fix the failing tests before completing your task."
    echo ""
    echo "Remaining checklist:"
    echo "  {linter_command}"
    exit 1
  else
    echo "✅ All affected tests passed."
  fi
fi

echo ""
echo "Remaining checklist:"
echo "  {linter_command}"
```

## How the tester uses it

The tester agent's system prompt should reference this script:

```
## Verify Script

Run `scripts/verify.sh` (or `bash scripts/verify.sh`) to identify and run all affected tests.
If tests fail and the failures are caused by implementation bugs (not test issues),
report back to the orchestrator so the coder can fix.
```

**Do NOT register this as a Stop hook.** Running tests on every response is wasteful — it runs even when editing config files or answering questions. The tester agent owns test execution as part of the workflow.
