// dp is the DevPit CLI — a sequential multi-agent pipeline for AI coding agents.
//
// It spawns specialized agents (architect, coder, tester, reviewer, design-qa)
// one at a time in tmux sessions, passing context between steps.
//
// Usage:
//
//	dp pipeline "Add a health check endpoint"
//	dp setup-agents
//	dp pipeline agent architect "Design a caching layer"
//	dp pipeline status
//	dp pipeline peek coder
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/spf13/cobra"
	"github.com/colbymchenry/devpit/internal/config"
	"github.com/colbymchenry/devpit/internal/pipeline"
	"github.com/colbymchenry/devpit/internal/setupagents"
	"github.com/colbymchenry/devpit/internal/tmux"
)

var version = "dev"

func main() {
	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

// --- Root ---

var rootCmd = &cobra.Command{
	Use:   "dp",
	Short: "DevPit — sequential agent pipeline CLI",
	Long: `DevPit runs specialized AI agents in sequence on a task:
  architect → coder → tester → reviewer → design-qa

Each agent runs in its own tmux session. Agents are defined by
.claude/agents/*.md files (generated by 'dp setup-agents').`,
	Version: version,
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		// Skip tmux check for commands that don't need it (help, version, completion).
		if cmd.Name() == "help" || cmd.Name() == "version" || cmd.Name() == "completion" {
			return nil
		}
		if _, err := exec.LookPath("tmux"); err != nil {
			fmt.Fprintln(os.Stderr, "tmux is required but not installed.")
			fmt.Fprintln(os.Stderr)
			switch runtime.GOOS {
			case "darwin":
				fmt.Fprintln(os.Stderr, "  brew install tmux")
			case "linux":
				fmt.Fprintln(os.Stderr, "  Ubuntu/Debian:  sudo apt install tmux")
				fmt.Fprintln(os.Stderr, "  Fedora/RHEL:    sudo dnf install tmux")
				fmt.Fprintln(os.Stderr, "  Arch:           sudo pacman -S tmux")
			default:
				fmt.Fprintln(os.Stderr, "  Install tmux for your platform: https://github.com/tmux/tmux")
			}
			fmt.Fprintln(os.Stderr)
			fmt.Fprintln(os.Stderr, "Install tmux and try again.")
			os.Exit(1)
		}
		return nil
	},
}

// --- Pipeline flags ---

var (
	flagAgent      string
	flagTimeout    time.Duration
	flagMaxRetries int
	flagSkipReview bool
	flagSkipQA     bool
	flagDetach     bool
	flagPeekLines  int
)

func init() {
	// dp pipeline
	rootCmd.AddCommand(pipelineCmd)
	pipelineCmd.Flags().StringVar(&flagAgent, "agent", "", "AI runtime preset (claude, gemini, codex, etc.)")
	pipelineCmd.Flags().DurationVar(&flagTimeout, "timeout", pipeline.DefaultStepTimeout, "Max time per pipeline step")
	pipelineCmd.Flags().IntVar(&flagMaxRetries, "retries", pipeline.DefaultMaxRetries, "Max coder↔tester/design-qa retries")
	pipelineCmd.Flags().BoolVar(&flagSkipReview, "skip-review", false, "Skip the reviewer step")
	pipelineCmd.Flags().BoolVar(&flagSkipQA, "skip-qa", false, "Skip the design-qa step")

	// dp pipeline agent
	pipelineCmd.AddCommand(agentCmd)
	agentCmd.Flags().BoolVar(&flagDetach, "detach", false, "Spawn without attaching")
	agentCmd.Flags().StringVar(&flagAgent, "agent", "", "AI runtime preset")

	// dp pipeline status
	pipelineCmd.AddCommand(statusCmd)

	// dp pipeline peek
	pipelineCmd.AddCommand(peekCmd)
	peekCmd.Flags().IntVarP(&flagPeekLines, "lines", "n", 50, "Number of lines to capture")

	// dp setup-agents
	rootCmd.AddCommand(setupAgentsCmd)
	setupAgentsCmd.Flags().StringVar(&flagAgent, "agent", "", "AI runtime preset (default: claude)")
}

// --- dp pipeline ---

var pipelineCmd = &cobra.Command{
	Use:   "pipeline <task>",
	Short: "Run sequential agent pipeline on a task",
	Long: `Run a sequential agent pipeline: architect → coder → tester → reviewer → design-qa.

Each step spawns a single AI agent in a tmux session, waits for completion,
captures output, and passes context to the next step.

Two retry loops:
  - Coder ↔ Tester: if tests fail, coder fixes and tester re-runs
  - Coder ↔ Design QA: if visual issues found, coder fixes and QA re-checks

Design-qa is only included if .claude/agents/design-qa.md exists.

Examples:
  dp pipeline "Add a health check endpoint"
  dp pipeline "Fix the login form validation" --retries 2
  dp pipeline "Refactor auth module" --skip-qa --agent gemini`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		task := args[0]
		projectDir, err := os.Getwd()
		if err != nil {
			return err
		}

		steps := pipeline.DiscoverPipeline(projectDir)
		if len(steps) == 0 {
			return fmt.Errorf("no agent files found in .claude/agents/\nRun 'dp setup-agents' first")
		}

		fmt.Fprintf(os.Stderr, "Pipeline: %s\n", strings.Join(steps, " → "))
		fmt.Fprintf(os.Stderr, "Task: %s\n\n", task)

		result, err := pipeline.Run(pipeline.PipelineOpts{
			Task:        task,
			ProjectDir:  projectDir,
			AgentPreset: flagAgent,
			StepTimeout: flagTimeout,
			MaxRetries:  flagMaxRetries,
			SkipReview:  flagSkipReview,
			SkipQA:      flagSkipQA,
			OnStepStart: func(step string, attempt int) {
				if attempt > 1 {
					fmt.Fprintf(os.Stderr, "→ %s (attempt %d)\n", step, attempt)
				} else {
					fmt.Fprintf(os.Stderr, "→ %s\n", step)
				}
			},
			OnStepDone: func(step string, passed bool, output string) {
				if passed {
					fmt.Fprintf(os.Stderr, "  done\n")
				} else {
					fmt.Fprintf(os.Stderr, "  failed\n")
				}
			},
		})
		if err != nil {
			return err
		}

		fmt.Print(pipeline.FormatSummary(result))
		return nil
	},
}

// --- dp pipeline agent ---

var agentCmd = &cobra.Command{
	Use:   "agent <name> <prompt>",
	Short: "Run a single agent interactively in tmux",
	Long: `Spawn a single pipeline agent and attach to it.

Examples:
  dp pipeline agent architect "Design a caching layer"
  dp pipeline agent coder "Implement the plan" --detach`,
	Args: cobra.ExactArgs(2),
	RunE: func(cmd *cobra.Command, args []string) error {
		name, prompt := args[0], args[1]
		projectDir, err := os.Getwd()
		if err != nil {
			return err
		}

		cfg, err := pipeline.LoadAgentConfig(projectDir, name)
		if err != nil {
			return fmt.Errorf("agent %q not found: %w", name, err)
		}

		fullPrompt := pipeline.BuildPrompt(cfg.Body, prompt, nil)
		t := tmux.NewTmux()
		session, err := pipeline.SpawnAgent(t, name, projectDir, fullPrompt, pipeline.SpawnOptions{
			AgentPreset: flagAgent,
		})
		if err != nil {
			return err
		}

		if flagDetach {
			fmt.Fprintf(os.Stderr, "Agent %q running in session %q\n", name, session)
			fmt.Fprintf(os.Stderr, "  peek:   dp pipeline peek %s\n", name)
			fmt.Fprintf(os.Stderr, "  attach: tmux attach -t %s\n", session)
			return nil
		}

		tmuxPath, err := exec.LookPath("tmux")
		if err != nil {
			return fmt.Errorf("tmux not found: %w", err)
		}
		return syscall.Exec(tmuxPath, []string{"tmux", "-u", "attach-session", "-t", session}, os.Environ()) //nolint:gosec // tmuxPath is from exec.LookPath
	},
}

// --- dp pipeline status ---

var statusCmd = &cobra.Command{
	Use:   "status",
	Short: "Show running pipeline agent sessions",
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		t := tmux.NewTmux()
		sessions, err := t.ListSessions()
		if err != nil {
			return err
		}

		var found bool
		for _, session := range sessions {
			if !strings.HasPrefix(session, pipeline.SessionPrefix) {
				continue
			}
			found = true
			agentName := strings.TrimPrefix(session, pipeline.SessionPrefix)

			state := "working"
			if t.IsIdle(session) {
				state = "idle"
			}

			lines, _ := t.CapturePaneLines(session, 5)
			lastLine := ""
			for i := len(lines) - 1; i >= 0; i-- {
				if trimmed := strings.TrimSpace(lines[i]); trimmed != "" {
					lastLine = trimmed
					break
				}
			}
			if len(lastLine) > 80 {
				lastLine = lastLine[:77] + "..."
			}

			fmt.Printf("  %-12s  %-8s  %s\n", agentName, state, lastLine)
		}

		if !found {
			fmt.Println("No pipeline sessions running.")
		}
		return nil
	},
}

// --- dp pipeline peek ---

var peekCmd = &cobra.Command{
	Use:   "peek <agent> [count]",
	Short: "View recent output from a pipeline agent",
	Long: `Examples:
  dp pipeline peek architect
  dp pipeline peek coder 100
  dp pipeline peek tester -n 200`,
	Args: cobra.RangeArgs(1, 2),
	RunE: func(cmd *cobra.Command, args []string) error {
		agentName := args[0]
		session := pipeline.SessionPrefix + agentName

		lines := flagPeekLines
		if len(args) > 1 {
			n, err := strconv.Atoi(args[1])
			if err != nil {
				return fmt.Errorf("invalid line count: %s", args[1])
			}
			lines = n
		}

		t := tmux.NewTmux()
		has, err := t.HasSession(session)
		if err != nil || !has {
			return fmt.Errorf("no active session for agent %q", agentName)
		}

		output, err := t.CapturePane(session, lines)
		if err != nil {
			return err
		}

		fmt.Print(output)
		return nil
	},
}

// --- dp setup-agents ---

var setupAgentsCmd = &cobra.Command{
	Use:   "setup-agents",
	Short: "Bootstrap specialized AI agents for this project",
	Long: `Detect project stack, interview you about preferences, and generate
tailored agent .md files in .claude/agents/.

After setup, use 'dp pipeline' to run the agent pipeline.

Examples:
  dp setup-agents
  dp setup-agents --agent gemini`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		projectDir, err := os.Getwd()
		if err != nil {
			return err
		}

		tmpDir, err := setupagents.WriteTemplatesToDir()
		if err != nil {
			return err
		}
		// Don't defer cleanup — tmux session needs the files after we exec.
		// The prompt file and templates will be cleaned up on next run or reboot.

		prompt := setupagents.SkillPrompt(tmpDir)

		// Write prompt to a temp file to avoid tmux command length limits.
		promptFile := filepath.Join(tmpDir, "prompt.txt")
		if err := os.WriteFile(promptFile, []byte(prompt), 0o600); err != nil {
			_ = os.RemoveAll(tmpDir)
			return fmt.Errorf("write prompt file: %w", err)
		}

		presetName := flagAgent
		if presetName == "" {
			presetName = "claude"
		}
		rc := config.RuntimeConfigFromPreset(config.AgentPreset(presetName))
		baseCommand := rc.BuildCommand()

		// Pass prompt via --append-system-prompt-file to avoid arg length limits.
		// Add a short initial message so claude starts immediately.
		command := fmt.Sprintf("exec env PIPELINE_AGENT=setup %s --append-system-prompt-file %s 'Your setup-agents instructions are already loaded in the system prompt. Follow them now. Analyze this project and interview me to generate agent files.'", baseCommand, quoteForShell(promptFile))

		t := tmux.NewTmux()
		session := pipeline.SessionPrefix + "setup-agents"
		_ = t.KillSession(session)

		if err := t.NewSessionWithCommand(session, projectDir, command); err != nil {
			return err
		}

		if err := t.AcceptStartupDialogs(session); err != nil {
			_ = err
		}

		fmt.Fprintf(os.Stderr, "Attaching to setup-agents session...\n")
		fmt.Fprintf(os.Stderr, "Answer the questions to generate your agent files.\n\n")

		tmuxPath, err := exec.LookPath("tmux")
		if err != nil {
			return fmt.Errorf("tmux not found: %w", err)
		}
		return syscall.Exec(tmuxPath, []string{"tmux", "-u", "attach-session", "-t", session}, os.Environ()) //nolint:gosec // tmuxPath is from exec.LookPath
	},
}

// quoteForShell wraps a string in single quotes, escaping embedded single quotes.
func quoteForShell(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
}
